name: "godot-ci export"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: clipboarder

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          pwd
          mkdir -v -p /build/windows
          godot --headless --verbose --export-release "Windows Desktop" /build/windows/$EXPORT_NAME.exe
          cd /build/windows
          ls -l
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: windows
          path: /build/windows/
      - name: Update latest tag and release files
        run: |
          cd /build/windows
          tar --create * -f file.zip --auto-compress
          git push --delete origin tagname || true
          git tag latest main && git push origin latest
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Gelissean/game_clipboarder/releases \
            -d '{"tag_name":"latest","target_commitish":"main","name":"latest","body":"Latest release","draft":false,"prerelease":false,"generate_release_notes":false}' \
            > result
          cat result | grep id
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: application/octet-stream" \
            "https://uploads.github.com/repos/Gelissean/game_clipboarder/releases/1/assets?name=windows.zip" \
            --data-binary "@windows.zip"

