name: "godot-ci export"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  
env:
  GODOT_VERSION: 4.1.3
  EXPORT_NAME: clipboarder

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.1.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          pwd
          mkdir -v -p /build/windows
          godot --headless --verbose --export-release "Windows Desktop" /build/windows/$EXPORT_NAME.exe
          cd /build/windows
          ls -l
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: windows
          path: /build/windows/
      - name: Update latest tag and release files
        run: |
          cd /build/windows
          tar --create * -f file.zip --auto-compress
          git push --delete origin tagname || true
          git tag latest main && git push origin latest
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/OWNER/REPO/releases \
            -f tag_name='latest' \
           -f target_commitish='master' \
           -f name='latest' \
           -f body='latest build' \
           -F draft=false \
           -F prerelease=false \
           -F generate_release_notes=false > result
          cat result | grep id
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            --hostname github.com \
            /repos/OWNER/REPO/game_clipboarder/1/assets?name=windows.zip \
            -f '@windows.zip'

